server:
  port: 8080
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: userapi
          uri: lb://userapi  # TODO: 将来从eureka获取uri
          predicates:
            - Path=/userapi/**
          filters:
            - StripPrefix=1

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/
